# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "ffuenf/ubuntu-15.10-server-amd64"
  config.vm.network "private_network", ip: "192.168.100.100"
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "../", "/srv/kurent-example", create:true,
    :mount_options => ['dmode=775', 'fmode=664']
  config.vm.provision :shell, path: "Vagrant-setup/bootstrap.sh"
end

#config.vm.forward_port 5432, 15432
#config.vm.forward_port 8088, 8088
#config.vm.forward_port 8080, 8080
